#!/bin/bash

ROOT_FOLDER=build/bin
VERSION=1.13.0
DETEKT_BIN=$ROOT_FOLDER/detekt-$VERSION
mkdir -p $ROOT_FOLDER
if [ ! -f "$DETEKT_BIN" ]; then
  echo "Please wait, first download..."
  rm -f $ROOT_FOLDER/detekt-*
  curl -sSL https://github.com/detekt/detekt/releases/download/v${VERSION}/detekt --output $DETEKT_BIN
  chmod a+x $DETEKT_BIN
fi

$DETEKT_BIN --config detekt.yml
echo "Done!"