# Android
android.builtInKotlin=false
android.enableJetifier=false
android.newDsl=false
android.nonTransitiveRClass=true
android.useAndroidX=true
# Gradle
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx8G"
org.gradle.parallel=true
# Kotlin
kotlin.code.style=official
kotlin.incremental=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
systemProp.org.gradle.internal.repository.initial.backoff=500
systemProp.org.gradle.internal.repository.max.retries=6
