rootProject.name = "Flipper App"
include(":components:bridge:api")
include(":components:bridge:impl")
include(":components:bridge:provider")
include(":components:bridge:service")
include(":components:bridge:protobuf")
include(":components:filemanager:api")
include(":components:filemanager:impl")
include(":components:core")
include(":components:pair:api")
include(":components:pair:impl")
include(":components:bottombar")
include(":components:info")
include(":instances:app")
