requiredParams:
  name: Flipper Blank Module
  description: Creates empty Gradle-module for general purposes

predefinedFeatures:
  - enableModuleCreationParams:
      defaultPackageNamePrefix: com.flipperdevices

widgets:
  - booleanParameter:
      id: needCompose
      name: Add Compose dependencies?
      help: Adds compose gradle plugin and compose deps
      default: false

  - booleanParameter:
      id: needFragment
      name: Add feature fragment?
      help: Adds fragment and default api implementation
      default: false

  - booleanParameter:
      id: isApi
      name: Is API submodule?
      help: If it is api module, we create only interface for instances
      default: false

  - booleanParameter:
      id: shouldGenerateDI
      name: Add di?
      help: Adds Dagger and Anvil deps, and create di component
      default: false

  - booleanParameter:
      id: needTest
      name: Add test?
      help: Adds testing library
      default: true

recipe:
  - mkDirs:
      - ${srcOut}

  - instantiate:
      from: root/gitignore.ftl
      to: ${rootOut}/.gitignore

  - instantiate:
      from: root/build.gradle.kts.ftl
      to: ${rootOut}/build.gradle.kts

  - predicate:
      validIf: ${shouldGenerateDI}
      commands:
        - mkDirs:
            - ${srcOut}/di/
        - instantiateAndOpen:
            from: root/src/app_package/di/BlankComponent.kt.ftl
            to: ${srcOut}/di/${__formattedModuleName}Component.kt

  - predicate:
      validIf: ${needCompose}
      commands:
        - mkDirs:
            - ${srcOut}/composable/
        - instantiateAndOpen:
            from: root/src/app_package/composable/ComposableBlank.kt.ftl
            to: ${srcOut}/composable/Composable${__formattedModuleName}.kt

  - predicate:
      validIf: ${needFragment}
      commands:
        - mkDirs:
            - ${srcOut}/fragments/
        - instantiateAndOpen:
            from: root/src/app_package/fragments/BlankFragment.kt.ftl
            to: ${srcOut}/fragments/${__formattedModuleName}Fragment.kt
        - mkDirs:
            - ${srcOut}/api/
        - instantiateAndOpen:
            from: root/src/app_package/api/BlankApiImpl.kt.ftl
            to: ${srcOut}/api/${__formattedModuleName}ApiImpl.kt

  - predicate:
      validIf: ${isApi}
      commands:
        - mkDirs:
            - ${srcOut}/
        - instantiateAndOpen:
            from: root/src/app_package/api/BlankApi.kt.ftl
            to: ${srcOut}/${__formattedModuleName}Api.kt