package com.flipperdevices.bridge.api.error

enum class FlipperBleServiceError {
    CONNECT_BLUETOOTH_DISABLED,
    CONNECT_BLUETOOTH_PERMISSION,

    SERVICE_VERSION_NOT_FOUND,
    SERVICE_INFORMATION_NOT_FOUND,
    SERVICE_SERIAL_NOT_FOUND,

    SERVICE_VERSION_FAILED_INIT,
    SERVICE_INFORMATION_FAILED_INIT,
    SERVICE_SERIAL_FAILED_INIT,
}
