import com.flipperdevices.buildlogic.ApkConfig.VERSION_NAME
import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("flipper.lint")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("flipper.multiplatform-dependencies")
    id("com.google.devtools.ksp")
    id("dev.zacsweers.anvil")
}

kotlin {
    jvm("desktop")

    sourceSets {
        val desktopMain by getting
        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.dagger)
            implementation(libs.anvil.utils.annotations)
        }
    }
}

includeCommonKspConfigurationTo("kspDesktop")

compose.desktop {
    application {
        mainClass = "com.flipperdevices.bridge.connection.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Flipper App"
            packageVersion = project.VERSION_NAME
                .split(".")
                .let { semVers ->
                    // minimum major version for desktop is 1
                    val major = semVers.getOrNull(0)
                        ?.toIntOrNull()
                        ?.coerceAtLeast(1)
                        ?: 1
                    val minor = semVers.getOrNull(1) ?: 0
                    // If generated on CI - getting autogenerated last number first
                    val patch = semVers.getOrNull(3)
                        ?: semVers.getOrNull(2)
                        ?: 0
                    "$major.$minor.$patch"
                }
        }
    }
}

commonDependencies {
    implementation(projects.components.bridge.connection.sample.shared)

    implementation(libs.kotlin.coroutines.swing)
}

anvil {
    useKsp(
        contributesAndFactoryGeneration = true,
        componentMerging = true,
    )
}

dependencies {
    ksp(libs.dagger.compiler)
    ksp(libs.anvil.utils.compiler)
}
