package com.flipperdevices.core.ui.navigation

enum class FeatureScreenRootRoute {
    FILE_MANAGER,
    ARCHIVE_SHARE_BOTTOMSHEET,
    WEAR_KEYS_LIST,
    WEAR_SETUP,
    WEAR_EMULATE,
    MFKEY32,
    HUB,
    NFC_ATTACKS,
    DEVICE_INFO,
    OPTIONS,
    SCREEN_STREAMING,
    STRESS_TEST,
    FAP_HUB_MAIN,
    FAP_HUB_SEARCH,
    FAP_HUB_CATEGORY,
    FAP_HUB_APPSCREEN,
    SEARCH_ARCHIVE,
    ARCHIVE,
    KEY_SCREEN,
    CATEGORY_KEY_SCREEN,
    NFC_EDITOR,
    KEY_EDIT_SCREEN,
    FIRST_PAIR,
    WIDGET
}
