name: Check changelog changed
on:
  workflow_call:

jobs:
  changelog_changes:
    name: "Checking that changelog has changed"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Get change status for CHANGELOG.md
        id: changed-changelog
        uses: tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf # v45.0.4
        with:
          files: CHANGELOG.md
      - name: Failed if changelog not changed
        if: github.event.pull_request.user.login != 'renovate[bot]' && steps.changed-changelog.outputs.any_changed != 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: core.setFailed('CHANGELOG.md has not changed! You need to write human-readable changes in each Pull Request')
