name: firebase

on:
  push:
    branches:
      - 'ci/firebase'

jobs:
  build_internal_release:
    name: Build Internal AAB and APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build release
        run: ./gradlew :instances:app:assembleInternal :instances:app:bundleInternal -Dversion_code=${{ github.run_number }} -Dversion_name="0.1.${{ github.run_number }}"
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: instances/app/build/outputs/bundle/internal
          signingKeyBase64: ${{ secrets.SIGNING_KEY_TEST }}
          alias: ${{ secrets.KEY_ALIAS_TEST }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD_TEST }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD_TEST }}
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: instances/app/build/outputs/apk/internal
          signingKeyBase64: ${{ secrets.SIGNING_KEY_TEST }}
          alias: ${{ secrets.KEY_ALIAS_TEST }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD_TEST }}
          keyPassword: ${{ secrets.KEY_ALIAS_PASSWORD_TEST }}
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            ${{ steps.sign_aab.outputs.signedReleaseFile }}
            ${{ steps.sign_apk.outputs.signedReleaseFile }}
            instances/app/build/outputs/mapping/internal/mapping.txt
  upload_to_firebase:
    name: Upload to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: build_internal_release
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: artifacts
      - run: echo ${{steps.download.outputs.download-path}}
      - run: ls ${{steps.download.outputs.download-path}}
      - run: ls ${{steps.download.outputs.download-path}}/bundle
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: ${{steps.download.outputs.download-path}}/bundle/app-internal.aab