name: "Validate Gradle Wrapper"
on: [ push, pull_request ]

jobs:
  validation:
    name: "Validation"
    runs-on: [self-hosted, AndroidShell]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3