name: Pull Request CI - Changelog

on:
  pull_request:
    branches:
      - 'dev'

# Concurrency strategy:
#   github.workflow: distinguish this workflow from others
#   github.event_name: distinguish `push` event from `pull_request` event
#   github.ref_name: distinguish branch
#   github.repository: distinguish owner+repository
#
# Reference:
#   https://docs.github.com/en/actions/using-jobs/using-concurrency
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{github.ref_name}}-${{github.repository}}
  cancel-in-progress: true

jobs:
  changelog_changes:
    name: "Checking that changelog has changed"
    runs-on: [self-hosted, AndroidShell]
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          submodules: 'recursive'
      - name: Get change status for CHANGELOG.md
        id: changed-changelog
        uses: tj-actions/changed-files@58ae566dc69a926834e4798bcfe0436ff97c0599 # v26.1
        with:
          files: CHANGELOG.md
      - name: Failed if changelog not changed
        if: github.event.pull_request.user.login != 'renovate[bot]' && steps.changed-changelog.outputs.any_changed != 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: core.setFailed('CHANGELOG.md has not changed! You need to write human-readable changes in each Pull Request')
